@startuml
title As a User I want to add all ingredients from a recipe
actor User as User
participant "RecipesFragment" as GalleryFragment
participant "RecipesViewModel" as GalleryViewModel
participant "ShoppingCartRequest" as ShoppingCart
participant "HttpClient" as HttpClient
database "Spoonacular API" as Server
participant "Convert" as Convert
Note left of GalleryFragment: SharedPreferences\n(username, hash)

User -> GalleryFragment: click add all
GalleryFragment -> GalleryViewModel: sendIngredientToBasket( ingredientName,totalIngredients,username,hash)
GalleryViewModel->ShoppingCart:ShoppingCartRequest(ingredientName)
ShoppingCart-->GalleryViewModel: shoppingCart
GalleryViewModel->Convert:Convert.convertToJson(shoppingCart)
Convert-->GalleryViewModel:ingredientJson

activate HttpClient

GalleryViewModel -> HttpClient: postRequest(shoppingUrl, ingredientJson, callback)
activate Server

HttpClient->Server:POST request
Server-->"HttpClient":response

deactivate Server
HttpClient --> GalleryViewModel: response success
deactivate HttpClient
GalleryViewModel -> GalleryViewModel: update successfulAdditions counter
GalleryViewModel -> GalleryViewModel: check if all ingredients added successfully
GalleryViewModel -> GalleryViewModel: postValue(success)
deactivate GalleryViewModel
GalleryViewModel -> GalleryFragment: observe getSuccessfulAdditionLiveData()
activate GalleryFragment
GalleryFragment -> User: Display success or failure message
deactivate GalleryFragment

@enduml
