@startuml
autoactivate on
autonumber
title As a User i want to register an account
autonumber
actor "User" as US
participant registerPage as RP
participant "UserDTO" as  DTO
participant "Converter" as CV
participant Utils as Utils
participant HttpClients as HTTP

participant "User" as User


US->RP:Inserts required data
RP-->US:checks if the data isn´t null
US->RP:makePostRequest()
RP->DTO:UserDTO(usernameEditText, firstNameEditText, lastNameEditText, emailEditText)
DTO-->RP:userDTO
RP->CV:convertToJson(userDTO)
CV-->RP:jsonBody
RP->Utils:
Utils-->RP:postURL
RP->HTTP:postRequest(postURL,jsonBody,callback)
alt postRequest == successful
HTTP-->RP:responseBody
RP->CV:convertFromJson(responseBody,User.class)
CV->User
User-->RP:user
RP->US:Account created with success
end

@enduml