@startuml
autoactivate on
autonumber
title As a User i want to register an account
autonumber
actor "User" as US
participant registerPage as RP
participant "UserRequest" as Request
participant "Converter" as CV

participant Utils as Utils
participant HttpClients as HTTP
database "SpoonAcular API" as Server
participant DTOMapper as Mapper


US->RP:Inserts required data
RP-->US:checks if the data isn´t null
US->RP:makePostRequest()
RP->Request:UserRequest(usernameEditText, firstNameEditText, lastNameEditText, emailEditText)
Request-->RP:userRequest
RP->CV:convertToJson(userRequest)
CV-->RP:jsonBody
RP->Utils:create URL from Utils
Utils-->RP:postURL
RP->HTTP:postRequest(postURL,jsonBody,callback)
HTTP->Server:POST request
Server-->HTTP:response
alt postRequest == successful
HTTP-->RP:responseBody
RP->CV:convertFromJson(responseBody,UserDTO.class)
CV-->RP:userResponse
RP->Mapper:DTOMapper<UserDTO,User> userDTOMapper
Mapper->Mapper:userDTOMapper.map(userResponse)
Mapper-->RP:User user
RP->US:Account created with success
end

@enduml