@startuml
left to right direction

actor User
rectangle "OnlineSupermarket"{
rectangle "Account" {
    User --> (Create an account)

}

rectangle "Recipe"{
User --> (Choose a recipe)
User -->(Show ingredient off a recipe)
}

rectangle "Shopping List" {

    User -->(Add a ingredient to the shopping list)
    User -->(Add all ingredients to the shopping list)

    User -->(Show the shopping list )
    User -->(Remove an item from the shopping list)
    User -->(Remove all items from the shopping list)

}
}

@enduml