 @startuml
left to right direction

actor User

rectangle "Acount" {
    User --> (Create an account)

}

rectangle "Recipe"{
User --> (Choose a recipe)
User -->(Show details about a ingredient)
User -->(Show substitutes of  a ingredient)
}

rectangle "Shooping List" {

    User -->(Add a recipe to the shopping list)
    User -->(Show the shopping list )
    User -->(Remove a item from the shopping list)
}


@enduml