@startuml
actor User as User
title As a User I want to add a ingredient from a recipe

participant "RecipesFragment" as GalleryFragment
participant "RecipesViewModel" as GalleryViewModel
participant "ShoppingCartRequest" as ShoppingCart

participant "HttpClient" as HttpClient
database "Spoonacular API" as Server
participant "Convert" as Convert
Note left of GalleryFragment: SharedPreferences\n(username, hash)

User -> GalleryFragment: onAddMarkClick(String title)
GalleryFragment -> GalleryViewModel: sendIngredientToBasket(title,1,username,hash)
GalleryViewModel->ShoppingCart:ShoppingCartRequest(ingredient)
ShoppingCart-->GalleryViewModel: shoppingCart
GalleryViewModel->Convert:Convert.convertToJson(shoppingCart)
Convert-->GalleryViewModel:ingredientJson

activate HttpClient

GalleryViewModel -> HttpClient: postRequest(shoppingUrl, ingredientJson, callback)
activate Server

HttpClient->Server:POST request
Server-->"HttpClient":response

deactivate Server
HttpClient --> GalleryViewModel: response success
deactivate HttpClient
GalleryViewModel -> GalleryViewModel: update successfulAdditions counter
GalleryViewModel -> GalleryViewModel: check if all ingredients added successfully
GalleryViewModel -> GalleryViewModel: postValue(success)
deactivate GalleryViewModel
GalleryViewModel -> GalleryFragment: observe getSuccessfulAdditionLiveData()
activate GalleryFragment
GalleryFragment -> User: Display success or failure message
deactivate GalleryFragment

@enduml
