@startuml
title As a User I want to see the different ingredients

actor User as User
participant "GalleryFragment" as GalleryFragment
participant "GalleryViewModel" as GalleryViewModel
participant "HttpClient" as HttpClient
database "Spoonacular API" as Server
participant "Convert" as Convert
participant "DTOMapper" as DTOMapper
participant "IngredientItemAdapter" as IngredientItemAdapter

User -> GalleryFragment: Click on a recipe item (Question Mark)
GalleryFragment -> GalleryViewModel: onQuestionMarkClick(id, title)
activate GalleryViewModel
GalleryViewModel -> HttpClient: getRequest(url, callback)
activate HttpClient
HttpClient -> Server: GET request for ingredients
activate Server
Server --> HttpClient: response
deactivate Server
HttpClient --> GalleryViewModel: receive response
deactivate HttpClient
GalleryViewModel -> Convert: convertFromJson(jsonResponse, RecepieInformationDTO.class)
activate Convert
Convert --> GalleryViewModel: recepieInformationDTO
deactivate Convert
alt if  recepieInformationDTO.getExtendedIngredients() != null && !recepieInformationDTO.getExtendedIngredients().isEmpty()
GalleryViewModel->GalleryViewModel:  List<ExtendedIngridientsDTO> extendedIngridientsDTOS
GalleryViewModel -> DTOMapper: DTOMapper(ExtendedIngridientsDTO -> Ingredients) ingredientMapper
activate DTOMapper
DTOMapper -> DTOMapper:  ingredientMapper.mapList(extendedIngridientsDTOS)
DTOMapper -> GalleryViewModel: ingredients
end
deactivate DTOMapper
GalleryViewModel -> GalleryViewModel: postValue(ingredients)
deactivate GalleryViewModel
GalleryViewModel -> GalleryFragment: observe getIngredientsLiveData()
activate GalleryFragment
GalleryFragment -> IngredientItemAdapter: updateData(ingredients)
activate IngredientItemAdapter
IngredientItemAdapter -> GalleryFragment: updated data
deactivate IngredientItemAdapter
GalleryFragment -> GalleryFragment: showIngredientsAlertDialog(ingredients)
GalleryFragment -> User: Display ingredients
deactivate GalleryFragment
@enduml
