@startuml
title As User i want to delete all items
actor User as User
participant "SlideshowFragment" as SlideshowFragment
participant "SlideshowViewModel" as SlideshowViewModel
participant "ShoppingAdapter" as ShoppingAdapter



User -> SlideshowFragment: presses delete all button
activate SlideshowFragment
SlideshowFragment -> SlideshowViewModel: Live Data

SlideshowFragment -> SlideshowViewModel: deleteAllItems(username, hash)
activate SlideshowViewModel

SlideshowViewModel -> SlideshowViewModel: iterate through cartItems
loop for each cartItem
    SlideshowViewModel -> SlideshowViewModel: get cartItem ID
    SlideshowViewModel -> SlideshowViewModel: call deleteItem(username, hash, itemId)
SlideshowViewModel-->SlideshowFragment: getDeletedItemLiveData().observe()
deactivate SlideshowViewModel

activate SlideshowFragment
SlideshowFragment -> ShoppingAdapter: handleDeletedItem(deletedItemId)
activate ShoppingAdapter
end loop
ShoppingAdapter -> SlideshowFragment: remove all items
deactivate ShoppingAdapter
SlideshowFragment -> SlideshowFragment: updateTotalCostView(calculateTotalCost(cartItems))
SlideshowFragment --> User: Update UI with Data and display it

deactivate SlideshowFragment

@enduml
