@startuml
autoactivate on
autonumber
title As a User i want to see   recipes
autonumber
actor "User" as US
participant GalleryFragment as RP
participant HttpClients as HTTP
participant "Converter" as CV

participant "RecipeDTO" as  DTO
participant "RecipeItemDTO" as DTO2

participant DTOMapper as Mapper

participant "RecipeItem" as User
participant RecipeItemAdapter as SP

US->RP:Inserts required data
RP-->US:checks if the data isn´t null
US->RP:getRecepie(String urlApi)

RP->HTTP:.getRequest(urlApi,new Callback)
alt postRequest == successful
HTTP-->RP:response
RP->RP:jsonResponse = response.body().string();
RP->CV:convertFromJson(jsonResponse,RecipeDTO.class)
CV->DTO:convert to RecepieDTO
DTO-->RP:recipeDTO
RP->DTO2:recipeDTO.getResults();
DTO2-->RP: List<RecipeItemDTO> recipeItemDTOS
RP->Mapper: DTOMapper<RecipeItemDTO, RecipeItem>
Mapper-->RP:recipeItemMapper
RP->User:recipeItemMapper.mapList(recipeItemDTOS)
User-->RP:List<RecipeItem> recipes
RP->SP:recipeItemAdapter.updateData(recipes)
SP-->RP:updates view
end
RP-->US:shows recipies


@enduml