@startuml
actor User as User
participant "Android Fragment" as Fragment

participant "GalleryFragment" as GalleryFragment
participant "GalleryViewModel" as GalleryViewModel
participant "HttpClient" as HttpClient
database "Spoonacular API" as Server
participant "Convert" as Convert
participant "DTOMapper" as DTOMapper
participant "RecipeItemAdapter" as RecipeItemAdapter
User->Fragment:start
Note left of Fragment: SharedPreferences\n(username, hash)
Fragment->GalleryFragment: onCreate
GalleryFragment -> GalleryViewModel: observe LiveData
GalleryFragment -> GalleryViewModel: getRecipe(url)
activate GalleryViewModel
GalleryViewModel -> HttpClient: getRequest(url, callback)
activate HttpClient
HttpClient -> Server: GET request
activate Server
Server --> HttpClient: response
deactivate Server
HttpClient --> GalleryViewModel: receive response
deactivate HttpClient
GalleryViewModel -> Convert: convertFromJson(jsonResponse, RecipeDTO.class)
activate Convert
Convert --> GalleryViewModel: recipeDTO
deactivate Convert

alt recipeDTO.getResults() not empty then
    GalleryViewModel -> GalleryViewModel: extract RecipeItemDTO
    GalleryViewModel -> GalleryViewModel: create a List<RecepiItemDTO> recipeItemDTOS

    GalleryViewModel -> DTOMapper:DTOMapper(RecipeItemDTO -> RecipeItem)

    activate DTOMapper
    DTOMapper -> DTOMapper: recipeItemMapper.mapList(recipeItemDTOS)
    DTOMapper-->GalleryViewModel:recipes
deactivate DTOMapper
end
GalleryViewModel -> GalleryViewModel: postValue(recipes)
deactivate GalleryViewModel
GalleryViewModel -> GalleryFragment: observe getRecipeItemsLiveData()
activate GalleryFragment
GalleryFragment -> RecipeItemAdapter: updateData(recipes)
activate RecipeItemAdapter
RecipeItemAdapter -> GalleryFragment: updated data
deactivate RecipeItemAdapter
GalleryFragment -> GalleryFragment: display recipe items in RecyclerView
GalleryFragment --> Fragment: Update UI with Data
deactivate GalleryFragment
Fragment --> User: Display Updated UI
@enduml
